spring:
  application:
    name: Filmupia
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true

  # File Upload Settings
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 2MB
      max-request-size: 3MB

# JSON Web Token (JWT)
jwt:
  secret_key: ${JWT_SECRET_KEY}
  expiration_time: ${JWT_EXPIRATION_TIME}
  refresh_expiration_time: ${JWT_REFRESH_TOKEN_EXPIRATION}

cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  secretKey: ${CLOUDINARY_API_SECRET}

# Port Configuration
server:
  port: 9000