spring:
  application:
    name: Filmupia
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true

  # File Upload Settings
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 2MB
      max-request-size: 3MB

# Port Configuration
server:
  port: 9000